// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInteractionM = "sms_interaction"

// InteractionM mapped from table <sms_interaction>
type InteractionM struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InteractionID string    `gorm:"column:interaction_id;not null;index:INDEX_INTERACTION_ID,priority:1" json:"interaction_id"`
	Mobile        string    `gorm:"column:mobile;not null;index:INDEX_MOBILE_AND_CONTENT,priority:1" json:"mobile"`
	Content       string    `gorm:"column:content;not null;index:INDEX_MOBILE_AND_CONTENT,priority:2" json:"content"`
	Param         string    `gorm:"column:param" json:"param"`
	Provider      string    `gorm:"column:provider" json:"provider"`
	Account       string    `gorm:"column:account" json:"account"`
	ReceiveTime   time.Time `gorm:"column:receive_time" json:"receive_time"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InteractionM's table name
func (*InteractionM) TableName() string {
	return TableNameInteractionM
}
