// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistoryM = "sms_history"

// HistoryM mapped from table <sms_history>
type HistoryM struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Mobile            string    `gorm:"column:mobile" json:"mobile"`
	SendTime          time.Time `gorm:"column:send_time" json:"send_time"`
	Status            string    `gorm:"column:status" json:"status"`
	Content           string    `gorm:"column:content" json:"content"`
	Code              string    `gorm:"column:code" json:"code"`
	Message           string    `gorm:"column:message" json:"message"`
	MessageID         string    `gorm:"column:message_id" json:"message_id"`
	MessageTemplateID int64     `gorm:"column:message_template_id" json:"message_template_id"`
	Report            string    `gorm:"column:report" json:"report"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName HistoryM's table name
func (*HistoryM) TableName() string {
	return TableNameHistoryM
}
