// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplateM = "sms_template"

// TemplateM mapped from table <sms_template>
type TemplateM struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TemplateName string    `gorm:"column:template_name;not null" json:"template_name"`
	TemplateCode string    `gorm:"column:template_code;not null" json:"template_code"`
	Type         string    `gorm:"column:type;not null" json:"type"`
	Content      string    `gorm:"column:content;not null" json:"content"`
	Sign         string    `gorm:"column:sign" json:"sign"`
	Provider     string    `gorm:"column:provider" json:"provider"`
	Region       string    `gorm:"column:region;comment:国家地区" json:"region"` // 国家地区
	Providers    string    `gorm:"column:providers" json:"providers"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TemplateM's table name
func (*TemplateM) TableName() string {
	return TableNameTemplateM
}
