// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfigurationM = "sms_configuration"

// ConfigurationM mapped from table <sms_configuration>
type ConfigurationM struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConfigKey    string    `gorm:"column:config_key;not null" json:"config_key"`
	ConfigValue  string    `gorm:"column:config_value;not null" json:"config_value"`
	TemplateCode string    `gorm:"column:template_code;not null" json:"template_code"`
	Order        int32     `gorm:"column:order" json:"order"`
	CreateAt     time.Time `gorm:"column:create_at" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at" json:"update_at"`
}

// TableName ConfigurationM's table name
func (*ConfigurationM) TableName() string {
	return TableNameConfigurationM
}
